config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :commots
  resources :posts

  get '/random_question' => 'posts#get_random_question', as: :get_random_question

  root 'posts#index'

end

app/models/commot.rb
class Commot < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_attached_file :image_uno, styles: { large: "1600x1600>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image_uno, content_type: /\Aimage\/.*\z/

	has_attached_file :image_dos, styles: { large: "1600x1600>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image_dos, content_type: /\Aimage\/.*\z/

	has_attached_file :image_tres, styles: { large: "1600x600>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image_tres, content_type: /\Aimage\/.*\z/

	has_attached_file :image_quatro, styles: { large: "1600x600>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image_quatro, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/commots_controller.rb
class CommotsController < ApplicationController
  before_action :set_commot, only: [:show, :edit, :update, :destroy]

  # GET /commots
  # GET /commots.json
  def index
    @commots = Commot.all
  end

  # GET /commots/1
  # GET /commots/1.json
  def show
  end

  # GET /commots/new
  def new
    @commot = Commot.new
  end

  # GET /commots/1/edit
  def edit
  end

  # POST /commots
  # POST /commots.json
  def create
    @commot = Commot.new(commot_params)

    respond_to do |format|
      if @commot.save
        format.html { redirect_to @commot, notice: 'Commot was successfully created.' }
        format.json { render :show, status: :created, location: @commot }
      else
        format.html { render :new }
        format.json { render json: @commot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commots/1
  # PATCH/PUT /commots/1.json
  def update
    respond_to do |format|
      if @commot.update(commot_params)
        format.html { redirect_to @commot, notice: 'Commot was successfully updated.' }
        format.json { render :show, status: :ok, location: @commot }
      else
        format.html { render :edit }
        format.json { render json: @commot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commots/1
  # DELETE /commots/1.json
  def destroy
    @commot.destroy
    respond_to do |format|
      format.html { redirect_to commots_url, notice: 'Commot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commot
      @commot = Commot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def commot_params
      params.require(:commot).permit(:post_id, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  def get_random_question

    if current_user.blockyy1 
      @block1 = Post.where("block =?", 1)
    end
    if current_user.blockyy2 
      @block2 = Post.where("block =?", 2)
    end
    if current_user.blockyy3 
      @block3 = Post.where("block =?", 3)
    end
    if current_user.blockyy4 
      @block4 = Post.where("block =?", 4)
    end
    if current_user.blockyy5 
      @block5 = Post.where("block =?", 5)
    end

    @eligibles = Array(@block1)+Array(@block2)+Array(@block3)+Array(@block4)+Array(@block5)

    @post = @eligibles.shuffle.sample
    if @post != nil
      @x = 0
      while ((current_user.rez.include?@post.id) && (@x < (@eligibles.length)))
        @post = @eligibles.shuffle.sample
        @x += 1
      end

      current_user.update_attributes(:rez => current_user.rez.push(@post.id))

      if current_user.rez.length == 11
        @temp = current_user.rez
        @temp.shift
        current_user.update_attributes(:rez => @temp)
      end
    end

    if @post != nil
      redirect_to @post
    else
      respond_to do |format|
        format.html { redirect_to root_url, notice: '< Please select at least 1 block.' }
        format.json { render :show, status: :ok, location: @post }
      end
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to root_url, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:question, :body, :image_uno, :image_dos, :image_tres, :image_quatro, :block, :label, :marker)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_url, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:blockyy1, :blockyy2, :blockyy3, :blockyy4, :blockyy5, :rez)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commots_helper.rb
module CommotsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_alerts.html.erb
<div class = "flash-message ">
	<% flash.each do |name, msg| %>
	  <% if msg.is_a?(String) %>
		<div data-alert class="alert-box notice">
	      <%= content_tag :div, msg %>
	      <a href="#" class="close">&times;</a>
	    </div>
	  <% end %>
    <% flash.clear %>
	<% end %>
</div>

app/views/application/_blocky.html.erb
<%= simple_form_for(current_user, :url => registration_path(current_user)) do |f| %>
  <div class="field">
    <%= f.input :blocky, as: :integer%>
  </div>
  <%= f.button :submit %>
<% end %>

app/views/application/_topBar.html.erb
<div class="contain-to-grid sticky">
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">UR Histo</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>


        <!-- DON"T DISPLAY ANYTHING IF NO CURRENT USER -->
      <% if current_user %>

  <section class="top-bar-section">
        <!-- Left Nav Section -->
    
    <ul class="left">
      <%= render 'application/alerts' %>

      <!-- Select Blocks Tab -->
       <li class="has-dropdown active">
        <a href="#">Select blocks</a>
        <%= render 'application/blocky' %>
      </li>
    </ul>


    
    <!-- Right Nav Section -->
    <ul class="right">

      <!-- Answer Tab -->
      <% if @post != nil %>
        <% if @post.label != nil %>
          <li class="has-dropdown active active2 show-for-large-only">
            <span class = "active2"><a href="#">Answer</a></span>
            <ul class="dropdown">
              <li class = "active active2"><a href="#"><%= @post.label %></a></li>
            </ul>
          </li>
        <% end %>
      <% end %>


      <!-- Random Question Tab -->
      <li class = "active"><%= link_to "Random Question", :get_random_question, :class => "button", :as => :get_random_question, data: { no_turbolink: true }, :class => "li active" %></li>
     
      <% if user_signed_in? %>
        <li class = "show-for-large-only">
          <%= button_to "Logout", destroy_user_session_path, :class => "button alt5",  method: :delete %>
        </li>
      <% end %>

    </ul>
    
  </section>


      <% end %>
        <!-- END IF CURRENT_USER -->
</nav>
</div>

app/views/commots/_form.html.erb
<%= form_for(@commot) do |f| %>
  <% if @commot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commot.errors.count, "error") %> prohibited this commot from being saved:</h2>

      <ul>
      <% @commot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/commots/edit.html.erb
<h1>Editing Commot</h1>

<%= render 'form' %>

<%= link_to 'Show', @commot %> |
<%= link_to 'Back', commots_path %>

app/views/commots/index.html.erb
 

<h1>Listing Commots</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @commots.each do |commot| %>
      <tr>
        <td><%= commot.post_id %></td>
        <td><%= commot.body %></td>
        <td><%= link_to 'Show', commot %></td>
        <td><%= link_to 'Edit', edit_commot_path(commot) %></td>
        <td><%= link_to 'Destroy', commot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Commot', new_commot_path %>

app/views/commots/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %> 

<%= link_to 'Back', commots_path %>

app/views/commots/show.html.erb
 

<p>
  <strong>Post:</strong>
  <%= @commot.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @commot.body %>
</p>

<%= link_to 'Edit', edit_commot_path(@commot) %> |
<%= link_to 'Back', commots_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title> URMC Histology</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class = "row">
      <div class ="small-10 medium-4 small-centered columns">
        <%= render 'application/alerts' %>
      </div>
    </div>



    <%= render 'application/topBar' %>


          <div class = "heading show-for-medium-up" id = "heading">

<!-- 
            <div class = "small-6 medium-6 columns devise_links text-right fixed">
              <% if user_signed_in? %>

              <%= button_to "Logout", destroy_user_session_path, :class => "button alt2 right",  method: :delete %>
              <% if current_page?(root_url) %>
                <%= link_to "Random Question", :get_random_question, :class => "button", :as => :get_random_question, data: { no_turbolink: true } %>
              <% end %>
              <% else %>
                <%= button_to "Login", new_user_session_path, :class => "button alt right",  method: :get %>
                <%= button_to "Sign Up", new_user_registration_path, :class => "button alt2 right",  method: :get %>
              <% end %> -->

              
          </div>
          <!-- END NAVIGATION -->








    <div class = "row">
      <div class = "small-12 columns">
        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% if @post.image_uno_file_size != nil %>
  <%= image_tag @post.image_uno.url(:large) %>
<% end %>
  <div class="field">
    <%= f.input :marker %>
  </div>
<!--   <div class="field">
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div> -->
  <div class="field">
    <%= f.input :block, as: :integer%>
  </div>
  <div class="field">
    <%= f.input :label %>
  </div>
  <div class="field">
    <%= f.input :image_uno, as: :file %>
  </div>
  <div class="field">
    <%= f.input :image_dos, as: :file %>
  </div>
  <div class="field">
    <%= f.input :image_tres, as: :file %>
  </div>
  <div class="field">
    <%= f.input :image_quatro, as: :file %>
  </div>
  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class = "small-12 medium-6 columns small-text-center medium-text-left">
<h1>What Do I See??</h1>
</div>

<!--
<div class = "small-12 medium-6 columns small-text-center medium-text-right">
  <%= link_to "Random Question", :get_random_question, :class => "button", :as => :get_random_question, data: { no_turbolink: true } %>
</div> -->

<div class = "small-12 columns">

<div class = "Small-10 columns">
  <p class = "red"> Instructions: <br/><i>Use 'Select blocks' (top left) to choose which blocks you want to study. <br/>Click 'Random Question' (top right) to get an ID the organ question pulled from those blocks at random.</i></p>
</div>

<!--
<h3> All </h3>
<table>
  <thead>
    <tr>
      <th>Slide</th>
      <th> Block </th>
      <th> Marker </th>
      <th> Edit </th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.label, post %></td>
        <td><%= post.block %></td>
        <td><%= post.marker %> </td>
        <td><%= link_to 'Edit', edit_post_path(post) %> </td>
      </tr>
    <% end %>
  </tbody>
</table>
-->





<h3> Block 1 </h3>
<table>
  <thead>
    <tr>
      <!-- <th> Number </th> -->
      <!-- <th>Block</th> -->
      <th width="500">Slide #</th>
      <th width="200">Organ</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @posts.where(:block => 1).each do |post| %>
      <tr>
        <!-- <td><%= link_to post.id, post %> </td> -->
        <!-- <td><%= link_to post.block, post %></td> -->
        <td><%= link_to post.label, post %></td>
        <td><%= link_to post.marker, post %></td>
        <!-- <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>


<h3> Block 2 </h3>
<table>
  <thead>
    <tr>
      <!-- <th> Number </th> -->
      <!-- <th>Block</th> -->
      <th width="500">Slide #</th>
      <th width="200">Organ</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @posts.where(:block => 2).each do |post| %>
      <tr>
        <!-- <td><%= link_to post.id, post %> </td> -->
        <!-- <td><%= link_to post.block, post %></td> -->
        <td><%= link_to post.label, post %></td>
        <td><%= link_to post.marker, post %></td>
        <!-- <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>


<h3> Block 3 </h3>
<table>
  <thead>
    <tr>
      <!-- <th> Number </th> -->
      <!-- <th>Block</th> -->
      <th width="500">Slide #</th>
      <th width="200">Organ</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @posts.where(:block => 3).each do |post| %>
      <tr>
        <!-- <td><%= link_to post.id, post %> </td> -->
        <!-- <td><%= link_to post.block, post %></td> -->
        <td><%= link_to post.label, post %></td>
        <td><%= link_to post.marker, post %></td>
        <!-- <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>


<h3> Block 4 </h3>
<table>
  <thead>
    <tr>
      <!-- <th> Number </th> -->
      <!-- <th>Block</th> -->
      <th width="500">Slide #</th>
      <th width="200">Organ</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @posts.where(:block => 4).each do |post| %>
      <tr>
        <!-- <td><%= link_to post.id, post %> </td> -->
        <!-- <td><%= link_to post.block, post %></td> -->
        <td><%= link_to post.label, post %></td>
        <td><%= link_to post.marker, post %></td>
        <!-- <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>


<h3> Block 5 </h3>
<table>
  <thead>
    <tr>
      <!-- <th> Number </th> -->
      <!-- <th>Block</th> -->
      <th width="500">Slide #</th>
      <th width="200">Organ</th>
            <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @posts.where(:block => 5).each do |post| %>
      <tr>
        <!-- <td><%= link_to post.id, post %> </td> -->
        <!-- <td><%= link_to post.block, post %></td> -->
        <td><%= link_to post.label, post %></td>
        <td><%= link_to post.marker, post %></td>
        <!-- <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<h3> Not Categorized Yet </h3>
<table>
  <thead>
    <tr>
      <th width="500">Slide #</th>
      <th width="200">Organ</th>
      <!-- <th> Edit </th> -->
    </tr>
  </thead>

  <tbody>
    <% @posts.where(:block => 0).each do |post| %>
      <tr>

        <td><%= link_to post.label, post %></td>
        <td><%= link_to post.marker, post %></td>
        <!-- <td><%= link_to 'Edit', edit_post_path(post) %> </td> -->
      </tr>
    <% end %>
  </tbody>
</table>


<br>

</div>
<!-- <%= link_to 'New Post', new_post_path %> -->

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
 

<div class="row">
      <div class="small-12 columns">
        <h1>What Do I See?</h1>
      </div>
    </div>
    
    <div class="row">
      <div class="small-12 columns">
<% if @post.image_uno_file_size != nil %>
  <%= image_tag @post.image_uno.url(:large) %>
<% end %>
<% if @post.image_dos_file_size != nil%>
  <%= image_tag @post.image_dos.url(:large) %>
<% end %>
<% if @post.image_tres_file_size != nil%>
  <%= image_tag @post.image_tres.url(:large) %>
<% end %>
<% if @post.image_quatro_file_size != nil%>
  <%= image_tag @post.image_quatro.url(:large) %>
<% end %>
      </div>
    </div>

    <br/><br/>

    <div class = "row">
      <div class = "small-6 columns text-center small-centered">
        <a class = "button active2" data-dropdown="drop1" aria-controls="drop1" aria-expanded="false">Answer</a>
        <ul id="drop1" class="f-dropdown" data-dropdown-content aria-hidden="true" tabindex="-1">
          <li class = "active2"><a href="#" class = "active2"><span class = "active2"><%= @post.label %></span></a></li>
        </ul>
      </div>
    </div>




<div class = "row">
    <div class = "small-12 columns text-center">
      <br/><br/>
      <%= link_to "Random Question", :get_random_question, :class => "button", :as => :get_random_question, data: { no_turbolink: true } %>
      <br/><br/>
  </div>
  <div class = "small-12 columns text-center">
    <p><%= link_to "Ahh I need to study!", root_url %></p>
  </div>
</div>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :blockyy1, inline_label: "Block 1" %>
    <%= f.input :blockyy2, inline_label: "Block 2" %>
    <%= f.input :blockyy3, inline_label: "Block 3" %>
    <%= f.input :blockyy4, inline_label: "Block 4" %>
    <%= f.input :blockyy5, inline_label: "Block 5" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Blocky1</th>
      <th>Blocky2</th>
      <th>Blocky3</th>
      <th>Blocky4</th>
      <th>Blocky5</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.blocky1 %></td>
        <td><%= user.blocky2 %></td>
        <td><%= user.blocky3 %></td>
        <td><%= user.blocky4 %></td>
        <td><%= user.blocky5 %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Blocky1:</strong>
  <%= @user.blocky1 %>
</p>

<p>
  <strong>Blocky2:</strong>
  <%= @user.blocky2 %>
</p>

<p>
  <strong>Blocky3:</strong>
  <%= @user.blocky3 %>
</p>

<p>
  <strong>Blocky4:</strong>
  <%= @user.blocky4 %>
</p>

<p>
  <strong>Blocky5:</strong>
  <%= @user.blocky5 %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>